### ISSUE TITLE
CABLE build failing in CI

### ISSUE THREAD

**Issue by ccarouge** [ACCESS-NRI/build-ci#182]
I think the build-ci is broken for CABLE: https://github.com/CABLE-LSM/CABLE/actions/runs/12084305937/job/33699224998?pr=499

I think the GH_REF doesn't work for CABLE:
```
  env:
    PACKAGE_NAME: cable
    SPACK_YAML_LOCATION: $SPACK_ROOT/../environments/cable
    GH_REF: dev
```
I'm not sure where it comes from and if it's a problem here or something we need to specify on our end @CodeGat .
